apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
  name: styringsinfo-datafortelling
  namespace: tbd
  metadata:
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  schedule: "0 */1 * * *"
  env:
    - name: NADA_URL
      value: nada.intern.dev.nav.no
    - name: QUARTO_ID
      value: f9a63635-60dc-4fb0-87aa-104f18e0e3e2
    - name: GCP_TEAM_PROJECT_ID
      value: tbd-dev-7ff9
  envFrom:
    - secret: nada-token

  backoffLimit: 0
  secureLogs:
    enabled: true
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/bigquery.dataViewer
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/bigquery.jobUser
  accessPolicy:
    outbound:
      external:
      - host: nada.intern.dev.nav.no
